/**
 * @author sumit
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * Ans: 
 */
object Problem2 {
    def main(args: Array[String]) = {
      println((take(4000000000l,fibonacci(1,2) filter(_%2==0)).sum))
    }
    def take(n: Long, seq:Stream[Long]):Stream[Long] = {
      if(n <= 0) Stream.Empty else Stream.cons(seq.head,take(n-1, seq.tail))
    }
    def fibonacci(x1:Long, x2:Long):Stream[Long] = (x1) #:: fibonacci(x2,x1+x2)
}